### ISSUE TITLE
Any chance to get your book for Russian readers?

### ISSUE THREAD

**Issue by keshon** [bitfield/ftl-fundamentals#8]
There is no legal way to obtain copy of your book in Russia due to the situation. Is there any other ways of getting it? Thank you.

**Comment by bitfield** [comment]
I'm sorry to hear that, but you'll appreciate that it's something I have no control over, and there's nothing I can do on my part to make this possible for you. I would love for readers in Russia to have access to my books, but as you say, that is currently impossible.

However, if you can access my website, there are many tutorials that you might find helpful, including several extracts from the books: https://bitfieldconsulting.com/

**Comment by keshon** [comment]
Thank you.
